### ISSUE TITLE
collective.folderorder 1.4.1 needs to add to the zcml part of buildout.cfg to make it work

### ISSUE THREAD

**Issue by trevorgrantstuart** [collective/collective.folderorder#3]
I have added this to my eggs in buildout, ran buildout, and it still doesn't seem to install properly. It does not show up in the add-on section of my site as being available. It installs the Yaowfil part, but not the collective.folderorder.. I see others use wildcard.foldercontents, but that does not allow you to things I'm looking to use collective.folderorder for.

ANY help would be nice.. Maybe a bug? I've seen a lot of people with this issue.

Plone 4.3.3

trevor@prestontrail.org

**Comment by idgserpro** [comment]
Having to add the product to ZCML not seem right.

**Comment by idgserpro** [comment]
Fix: https://github.com/collective/collective.folderorder/commit/2f53dae1cc7141796eddf172373a18c89200a2f9
